name: Test crates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true

      - name: Cargo test
        run: cargo test

      - name: Cargo publish
        run: cargo publish || true
